# Site settings
title: Kautuk Raj
general_email: kautukraj@gmail.com
academic_email: kautuk.raj@iiitb.ac.in

description: > # this means to ignore newlines until "baseurl:"
  We are such stuff as dreams are made on, and our little life is rounded with a sleep. 

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://kautukraj.github.io" # the base hostname & protocol for your site

twitter_username: kautukr
github_username: kautukraj
linkedin_username: kautukraj
# facebook_username: kautukraj
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
